/**
 * Cloudflare Worker for decoding the legacy Base64 + AES-128-ECB payload.
 * Deploy with: npx wrangler deploy
 */
const LEGACY_KEY = new TextEncoder().encode('KVksL2jJ6eLOP7cX');
const BLOCK_SIZE = 16;

const INV_S_BOX = new Uint8Array([
  0x52,0x09,0x6a,0xd5,0x30,0x36,0xa5,0x38,0xbf,0x40,0xa3,0x9e,0x81,0xf3,0xd7,0xfb,
  0x7c,0xe3,0x39,0x82,0x9b,0x2f,0xff,0x87,0x34,0x8e,0x43,0x44,0xc4,0xde,0xe9,0xcb,
  0x54,0x7b,0x94,0x32,0xa6,0xc2,0x23,0x3d,0xee,0x4c,0x95,0x0b,0x42,0xfa,0xc3,0x4e,
  0x08,0x2e,0xa1,0x66,0x28,0xd9,0x24,0xb2,0x76,0x5b,0xa2,0x49,0x6d,0x8b,0xd1,0x25,
  0x72,0xf8,0xf6,0x64,0x86,0x68,0x98,0x16,0xd4,0xa4,0x5c,0xcc,0x5d,0x65,0xb6,0x92,
  0x6c,0x70,0x48,0x50,0xfd,0xed,0xb9,0xda,0x5e,0x15,0x46,0x57,0xa7,0x8d,0x9d,0x84,
  0x90,0xd8,0xab,0x00,0x8c,0xbc,0xd3,0x0a,0xf7,0xe4,0x58,0x05,0xb8,0xb3,0x45,0x06,
  0xd0,0x2c,0x1e,0x8f,0xca,0x3f,0x0f,0x02,0xc1,0xaf,0xbd,0x03,0x01,0x13,0x8a,0x6b,
  0x3a,0x91,0x11,0x41,0x4f,0x67,0xdc,0xea,0x97,0xf2,0xcf,0xce,0xf0,0xb4,0xe6,0x73,
  0x96,0xac,0x74,0x22,0xe7,0xad,0x35,0x85,0xe2,0xf9,0x37,0xe8,0x1c,0x75,0xdf,0x6e,
  0x47,0xf1,0x1a,0x71,0x1d,0x29,0xc5,0x89,0x6f,0xb7,0x62,0x0e,0xaa,0x18,0xbe,0x1b,
  0xfc,0x56,0x3e,0x4b,0xc6,0xd2,0x79,0x20,0x9a,0xdb,0xc0,0xfe,0x78,0xcd,0x5a,0xf4,
  0x1f,0xdd,0xa8,0x33,0x88,0x07,0xc7,0x31,0xb1,0x12,0x10,0x59,0x27,0x80,0xec,0x5f,
  0x60,0x51,0x7f,0xa9,0x19,0xb5,0x4a,0x0d,0x2d,0xe5,0x7a,0x9f,0x93,0xc9,0x9c,0xef,
  0xa0,0xe0,0x3b,0x4d,0xae,0x2a,0xf5,0xb0,0xc8,0xeb,0xbb,0x3c,0x83,0x53,0x99,0x61,
  0x17,0x2b,0x04,0x7e,0xba,0x77,0xd6,0x26,0xe1,0x69,0x14,0x63,0x55,0x21,0x0c,0x7d,
]);
const RCON = new Uint8Array([0,1,2,4,8,16,32,64,128,27,54]);

function multiply(a, b) {
  let value = 0;
  while (b) { if (b & 1) value ^= a; a = (a << 1) ^ (a & 0x80 ? 0x11b : 0); b >>>= 1; }
  return value;
}
function addRoundKey(state, keys, round) { for (let i = 0; i < 16; i++) state[i] ^= keys[round * 16 + i]; }
function inverseShiftRows(s) {
  const copy = s.slice();
  for (let row = 0; row < 4; row++) for (let col = 0; col < 4; col++) s[row + 4 * col] = copy[row + 4 * ((col - row + 4) % 4)];
}
function inverseSubBytes(s) { for (let i = 0; i < 16; i++) s[i] = INV_S_BOX[s[i]]; }
function inverseMixColumns(s) {
  for (let col = 0; col < 4; col++) {
    const i = col * 4; const [a,b,c,d] = [s[i],s[i+1],s[i+2],s[i+3]];
    s[i] = multiply(a,14)^multiply(b,11)^multiply(c,13)^multiply(d,9);
    s[i+1] = multiply(a,9)^multiply(b,14)^multiply(c,11)^multiply(d,13);
    s[i+2] = multiply(a,13)^multiply(b,9)^multiply(c,14)^multiply(d,11);
    s[i+3] = multiply(a,11)^multiply(b,13)^multiply(c,9)^multiply(d,14);
  }
}
function expandKey(key) {
  const keys = new Uint8Array(176); keys.set(key);
  for (let i = 16, word = 1; i < keys.length; i += 4) {
    let [a,b,c,d] = keys.slice(i - 4, i);
    if (i % 16 === 0) { [a,b,c,d] = [INV_S_BOX.indexOf(b), INV_S_BOX.indexOf(c), INV_S_BOX.indexOf(d), INV_S_BOX.indexOf(a)]; }
    // Use the forward S-box generated by inverse lookup only during key expansion.
    if (i % 16 === 0) { a ^= RCON[word++]; }
    keys[i] = keys[i - 16] ^ a; keys[i+1] = keys[i - 15] ^ b; keys[i+2] = keys[i - 14] ^ c; keys[i+3] = keys[i - 13] ^ d;
  }
  return keys;
}
function decryptLegacyPayload(encryptedBase64) {
  if (typeof encryptedBase64 !== 'string' || !encryptedBase64.trim()) throw new TypeError('请输入非空 Base64 密文。');
  const normalized = encryptedBase64.replace(/\s+/g, '');
  if (!/^[A-Za-z0-9+/]*={0,2}$/.test(normalized) || normalized.length % 4) throw new Error('请输入规范的 Base64 数据。');
  const binary = atob(normalized);
  if (!binary.length || binary.length % BLOCK_SIZE) throw new Error('AES-ECB 密文长度必须是 16 字节的整数倍。');
  const ciphertext = Uint8Array.from(binary, (char) => char.charCodeAt(0));
  const keys = expandKey(LEGACY_KEY); const plaintext = new Uint8Array(ciphertext.length);
  for (let offset = 0; offset < ciphertext.length; offset += BLOCK_SIZE) {
    const state = ciphertext.slice(offset, offset + BLOCK_SIZE);
    addRoundKey(state, keys, 10);
    for (let round = 9; round > 0; round--) { inverseShiftRows(state); inverseSubBytes(state); addRoundKey(state, keys, round); inverseMixColumns(state); }
    inverseShiftRows(state); inverseSubBytes(state); addRoundKey(state, keys, 0); plaintext.set(state, offset);
  }
  const padding = plaintext[plaintext.length - 1];
  if (padding < 1 || padding > BLOCK_SIZE || !plaintext.slice(-padding).every((byte) => byte === padding)) throw new Error('解密失败：密钥或 PKCS#7 填充无效。');
  return new TextDecoder('utf-8', { fatal: true }).decode(plaintext.slice(0, -padding));
}

function page() { return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>遗留载荷解密</title><style>body{max-width:960px;margin:3rem auto;padding:0 1rem;background:#f6f8fa;color:#1f2328;font:16px system-ui}textarea{box-sizing:border-box;width:100%;min-height:220px;padding:12px;border:1px solid #d0d7de;border-radius:6px;font:13px ui-monospace,monospace}button{margin:1rem 0;padding:.65rem 1rem;border:0;border-radius:6px;background:#0969da;color:white;font-weight:600;cursor:pointer}button:disabled{opacity:.6}#error{color:#cf222e;white-space:pre-wrap}label{display:block;margin:.75rem 0}</style><main><h1>遗留载荷解密</h1><p>仅用于已获授权的审计与迁移验证。输入 Base64 密文后点击解密。</p><label for="input">加密内容</label><textarea id="input" placeholder="粘贴 Base64 密文"></textarea><button id="decrypt">解密</button><p id="error" role="alert"></p><label for="output">解密结果</label><textarea id="output" readonly placeholder="解密后的文本会显示在这里"></textarea></main><script>const input=document.querySelector('#input'),output=document.querySelector('#output'),error=document.querySelector('#error'),button=document.querySelector('#decrypt');button.onclick=async()=>{error.textContent='';output.value='';button.disabled=true;try{const response=await fetch('/api/decrypt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ciphertext:input.value})});const body=await response.json();if(!response.ok)throw Error(body.error||'解密失败');output.value=body.plaintext;try{output.value=JSON.stringify(JSON.parse(body.plaintext),null,2)}catch{}}catch(e){error.textContent=e.message}finally{button.disabled=false}};</script></html>`; }

export default {
  async fetch(request) {
    const url = new URL(request.url);
    if (request.method === 'GET' && url.pathname === '/') return new Response(page(), { headers: { 'content-type': 'text/html; charset=UTF-8' } });
    if (request.method === 'POST' && url.pathname === '/api/decrypt') {
      try {
        const { ciphertext } = await request.json();
        return Response.json({ plaintext: decryptLegacyPayload(ciphertext) });
      } catch (error) {
        return Response.json({ error: error instanceof Error ? error.message : '解密失败。' }, { status: 400 });
      }
    }
    return new Response('Not Found', { status: 404 });
  },
};

export { decryptLegacyPayload };
